--- requires.
do
    s = require('my_sequins')
    l = require('lanes')
    c = require('curves')
    disting = require('ii_disting')
    sd6 = disting.sd6
    poly = disting.poly
    multi = disting.multisample
    er301 = require("ii_er301")
    nr = require('nr')
    zr = require('zr')
    er2 = require('er2')
    xr = require('xr')
    cr = require('cr')
    fh2 = require('fh2-qv')
    phasor = require('phasor')
    mc = require('mc')
    ms = require('ms')
    a = require('arranger')
end

lanes = {
    mc={
        {},
        {},
        {},
        {},
        {},
        {},
    },
    ms={
        {},
        {},
        {},
        {},
        {},
        {},
    },
    fh2={
        {},
        {},
        {},
        {},
    },
    multi = {
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
    },
}

mc_table = {
    { -- T1
        chance = nil,
        color = nil,
        contour = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        gate = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        punch = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        rhythm = nil,
        shape = nil,
        sweep = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T2
        chance = nil,
        color = nil,
        contour = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        gate = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        punch = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        rhythm = nil,
        shape = nil,
        sweep = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T3
        chance = nil,
        color = nil,
        contour = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        gate = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        punch = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        rhythm = nil,
        shape = nil,
        sweep = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T4
        chance = nil,
        color = nil,
        contour = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        gate = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        punch = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        rhythm = nil,
        shape = nil,
        sweep = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T5
        chance = nil,
        color = nil,
        contour = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        gate = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        punch = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        rhythm = nil,
        shape = nil,
        sweep = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T6
        chance = nil,
        color = nil,
        contour = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        gate = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        punch = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        rhythm = nil,
        shape = nil,
        sweep = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    },
    device=mc,
    name='mc',
}
mc1 = mc_table[1]
mc2 = mc_table[2]
mc3 = mc_table[3]
mc4 = mc_table[4]
mc5 = mc_table[5]
mc6 = mc_table[6]

ms_table = {
    { -- T1
        chance = nil,
        cutoff = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        loop = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        resonance = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        reverse = nil,
        rhythm = nil,
        sample_length = nil,
        sample_start = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T2
        chance = nil,
        cutoff = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        loop = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        resonance = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        reverse = nil,
        rhythm = nil,
        sample_length = nil,
        sample_start = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T3
        chance = nil,
        cutoff = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        loop = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        resonance = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        reverse = nil,
        rhythm = nil,
        sample_length = nil,
        sample_start = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { -- T4
        chance = nil,
        cutoff = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        loop = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        resonance = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        reverse = nil,
        rhythm = nil,
        sample_length = nil,
        sample_start = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { --T5
        chance = nil,
        cutoff = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        loop = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        resonance = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        reverse = nil,
        rhythm = nil,
        sample_length = nil,
        sample_start = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    }, { --T6
        chance = nil,
        cutoff = nil,
        decay = nil,
        delay_fb = nil,
        delay_send = nil,
        delay_time = nil,
        device = nil,
        duration = nil,
        level = nil,
        lfo_depth = nil,
        lfo_dest = nil,
        lfo_fade = nil,
        lfo_mult = nil,
        lfo_phase = nil,
        lfo_reset = nil,
        lfo_speed = nil,
        lfo_wave = nil,
        loop = nil,
        mute = nil,
        note = nil,
        pan = nil,
        pitch = nil,
        resonance = nil,
        reverb_send = nil,
        reverb_size = nil,
        reverb_tone = nil,
        reverse = nil,
        rhythm = nil,
        sample_length = nil,
        sample_start = nil,
        swing = nil,
        sync_rate = s {1 / 4},
        track_note = nil,
        velocity = nil,
        volume_dist = nil
    },
    device=ms,
    name='ms',
}
ms1 = ms_table[1]
ms2 = ms_table[2]
ms3 = ms_table[3]
ms4 = ms_table[4]
ms5 = ms_table[5]
ms6 = ms_table[6]

fh2_table = {
    { -- Voice 1
        rhythm=nil,
        note=nil,
        duration=nil,
        velocity=nil,
        sync_rate=s{1/4},
        mod=nil,
    },
    { -- Voice 2
        rhythm=nil,
        note=nil,
        duration=nil,
        velocity=nil,
        sync_rate=s{1/4},
        mod=nil,
    },
    { -- Voice 3
        rhythm=nil,
        note=nil,
        duration=nil,
        velocity=nil,
        sync_rate=s{1/4},
        mod=nil,
    },
    { -- Voice 4
        rhythm=nil,
        note=nil,
        duration=nil,
        velocity=nil,
        sync_rate=s{1/4},
        mod=nil,
    },
    device=fh2,
    name='fh2',
}
mod1 = fh2_table[1]
mod2 = fh2_table[2]
mod3 = fh2_table[3]
mod4 = fh2_table[4]

multi_table = {
    {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    }, {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    }, {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    }, {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    }, {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    }, {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    }, {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    }, {
        OUTPUT_MODES = nil,
        all_notes_off = nil,
        all_voices_off = nil,
        arg_range = nil,
        arp_mode = nil,
        arp_reset_input = nil,
        bend_input = nil,
        bend_range = nil,
        chord_enable = nil,
        chord_inversion = nil,
        chord_key = nil,
        chord_scale = nil,
        chord_shape = nil,
        duration = nil,
        env_time = nil,
        fine_tune = nil,
        folder = nil,
        gain = nil,
        gate_offset = nil,
        input_mode = nil,
        max_voices = nil,
        normalisation = nil,
        note = nil,
        note_off = nil,
        note_on = nil,
        note_pitch = nil,
        octave = nil,
        output_mode = nil,
        rhythm = nil,
        saturation = nil,
        scala_kbm = nil,
        scala_scl = nil,
        sustain = nil,
        sustain_mode = nil,
        sync_rate = s {1 / 4},
        transpose = nil,
        velocity = nil,
        velocity_curve = nil,
        voice = nil,
        voice_bend_input = nil,
        voice_detune = nil,
        voice_off = nil,
        voice_on = nil,
        voice_pitch = nil
    },
    device=multi,
    name='multi',
}
m1 = multi_table[1]
m2 = multi_table[2]
m3 = multi_table[3]
m4 = multi_table[4]
m5 = multi_table[5]
m6 = multi_table[6]
m7 = multi_table[7]
m8 = multi_table[8]

ACTIVE_INSTRUMENTS = {}
phase_division = 64
reset_rate = 16

function init()
    print('Initialized')
    phi = phasor(phase_division)
end

function r()
    for _, instrument in ipairs(ACTIVE_INSTRUMENTS) do
        for _, track in ipairs(instrument) do
            for _, value in pairs(track) do
                local vmt = getmetatable(value)
                if vmt and vmt.reset ~= nil then
                    value:reset()
                end
            end
        end
    end
end

local function reset()
    while true do
        clock.sync(reset_rate)
        r()
    end
end

function clock.transport.start()
    print("Transport Started")
    clock_ids = {}
    for _, instrument in ipairs(ACTIVE_INSTRUMENTS) do
        clock_ids[instrument.name] = {}
        for track=1, #instrument do
            clock_ids[instrument.name][track] = clock.run(step, instrument.name, instrument.device, instrument[track], track)
        end
    end
    -- reset_clock_id = clock.run(reset)
    sync_to_bar = false
end

sync_to_bar = true
function clock.transport.stop()
    sync_to_bar = true
    print("Transport Stopped")
    for inst, clocks in pairs(clock_ids) do
        for _, clock_id in ipairs(clocks) do
            clock.cancel(clock_id)
        end
    end
    -- clock.cancel(reset_clock_id)
    phi:reset()
end


local note_makers = {
    multi = function(channel, _)
        return {
            channel.note and channel.note() or nil,
            channel.velocity and channel.velocity() or nil,
            channel.duration and channel.duration() or nil,
        }
    end,
    mc = function(channel, track)
        return {
            track,
            channel.velocity and channel.velocity() or nil,
            channel.duration and channel.duration() or nil,
            channel.note and channel.note() or nil,
        }
    end,
    ms = function(channel, track)
        return {
            track,
            channel.velocity and channel.velocity() or nil,
            channel.duration and channel.duration() or nil,
            channel.note and channel.note() or nil,
        }
    end,
    fh2 =  function(channel, track)
        return  {
            track,
            channel.note and channel.note() or nil,
            channel.velocity and channel.velocity() or nil,
            channel.duration and channel.duration() or nil,
        }
    end,
}
local function make_note_table(name, channel, track)
    local note_maker = note_makers[name]
    return note_maker(channel, track)
end

function step(name, device, channel, track)
    while true do
        if sync_to_bar then
            clock.sync(4)
        else
            clock.sync(channel.sync_rate())
        end
        if channel.rhythm and channel.rhythm() then
            for field, value in pairs(channel) do
                if value and field ~= 'note' and field ~= 'rhythm' and field ~= 'sync_rate'  and field ~= 'velocity' and field ~= 'duration' then
                    local v = value(phi())
                    local lane = lanes[name][track][field]
                    if lane then
                        v = v + lane()
                    end
                    device[field](device, track, math.floor(v))
                end
            end
            device:note(make_note_table(name, channel, track))
        end
    end
end
